#!/usr/bin/env node
/**
 * BadUSB Script Generator for Flipper Zero
 * Generates BadUSB scripts from templates and user input
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

class BadUSBGenerator {
  constructor() {
    this.templates = {
      hello_world: {
        name: 'Hello World',
        description: 'Opens notepad and types a message',
        os: 'Windows',
        generate: (params) => this._generateHelloWorld(params)
      },
      open_url: {
        name: 'Open URL',
        description: 'Opens a web browser with specified URL',
        os: 'Windows',
        generate: (params) => this._generateOpenURL(params)
      },
      run_command: {
        name: 'Run Command',
        description: 'Opens PowerShell/CMD and runs a command',
        os: 'Windows',
        generate: (params) => this._generateRunCommand(params)
      },
      create_file: {
        name: 'Create File',
        description: 'Creates a text file with content',
        os: 'Windows',
        generate: (params) => this._generateCreateFile(params)
      },
      linux_terminal: {
        name: 'Linux Terminal Command',
        description: 'Opens terminal and runs a command',
        os: 'Linux',
        generate: (params) => this._generateLinuxCommand(params)
      }
    };
  }

  _generateHelloWorld(params) {
    const message = params.message || 'Hello from Flipper Zero!';
    return `REM Hello World Script
REM Generated by BadUSB Generator
REM Target: Windows

DELAY 1000
GUI r
DELAY 500
STRING notepad
ENTER
DELAY 1000
STRING ${message}
ENTER
`;
  }

  _generateOpenURL(params) {
    const url = params.url || 'https://example.com';
    return `REM Open URL Script
REM Generated by BadUSB Generator
REM Target: Windows

DELAY 1000
GUI r
DELAY 500
STRING ${url}
ENTER
`;
  }

  _generateRunCommand(params) {
    const command = params.command || 'echo Hello';
    const terminal = params.terminal || 'powershell';
    return `REM Run Command Script
REM Generated by BadUSB Generator
REM Target: Windows

DELAY 1000
GUI r
DELAY 500
STRING ${terminal}
ENTER
DELAY 1000
STRING ${command}
ENTER
DELAY 500
STRING exit
ENTER
`;
  }

  _generateCreateFile(params) {
    const filename = params.filename || 'output.txt';
    const content = params.content || 'File content';
    return `REM Create File Script
REM Generated by BadUSB Generator
REM Target: Windows

DELAY 1000
GUI r
DELAY 500
STRING cmd
ENTER
DELAY 1000
STRING echo ${content} > %USERPROFILE%\\Desktop\\${filename}
ENTER
DELAY 500
STRING exit
ENTER
`;
  }

  _generateLinuxCommand(params) {
    const command = params.command || 'echo Hello Linux!';
    return `REM Linux Terminal Command
REM Generated by BadUSB Generator
REM Target: Linux

DELAY 1000
CTRL ALT t
DELAY 500
STRING ${command}
ENTER
`;
  }

  listTemplates() {
    console.log('\nAvailable Templates:');
    console.log('====================');
    Object.keys(this.templates).forEach(key => {
      const template = this.templates[key];
      console.log(`\n${key}:`);
      console.log(`  Name: ${template.name}`);
      console.log(`  Description: ${template.description}`);
      console.log(`  OS: ${template.os}`);
    });
    console.log('');
  }

  generate(templateName, params, outputFile) {
    if (!this.templates[templateName]) {
      throw new Error(`Template '${templateName}' not found`);
    }

    const script = this.templates[templateName].generate(params);

    if (outputFile) {
      fs.writeFileSync(outputFile, script);
      console.log(`✓ Script generated: ${outputFile}`);
    } else {
      console.log('\nGenerated Script:');
      console.log('=================');
      console.log(script);
    }

    return script;
  }
}

async function interactive() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  const question = (prompt) => new Promise((resolve) => {
    rl.question(prompt, resolve);
  });

  const generator = new BadUSBGenerator();

  console.log('\n╔════════════════════════════════════════════╗');
  console.log('║  Flipper Zero BadUSB Script Generator     ║');
  console.log('╚════════════════════════════════════════════╝\n');

  generator.listTemplates();

  const templateName = await question('Select template: ');
  
  if (!generator.templates[templateName]) {
    console.log('Invalid template name');
    rl.close();
    return;
  }

  const params = {};

  // Get template-specific parameters
  if (templateName === 'hello_world') {
    params.message = await question('Enter message: ');
  } else if (templateName === 'open_url') {
    params.url = await question('Enter URL: ');
  } else if (templateName === 'run_command') {
    params.terminal = await question('Terminal (powershell/cmd): ');
    params.command = await question('Enter command: ');
  } else if (templateName === 'create_file') {
    params.filename = await question('Filename: ');
    params.content = await question('File content: ');
  } else if (templateName === 'linux_terminal') {
    params.command = await question('Enter command: ');
  }

  const outputFile = await question('Output file (or press Enter to display): ');

  try {
    generator.generate(templateName, params, outputFile || null);
  } catch (error) {
    console.error('Error:', error.message);
  }

  rl.close();
}

function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
    console.log('Flipper Zero BadUSB Script Generator');
    console.log('\nUsage:');
    console.log('  node badusb_generator.js                    # Interactive mode');
    console.log('  node badusb_generator.js --list             # List templates');
    console.log('  node badusb_generator.js <template> [opts]  # Generate from template');
    console.log('\nExamples:');
    console.log('  node badusb_generator.js hello_world --message "Hello!" --output hello.txt');
    console.log('  node badusb_generator.js open_url --url "https://github.com" --output url.txt');
    return;
  }

  const generator = new BadUSBGenerator();

  if (args[0] === '--list' || args[0] === '-l') {
    generator.listTemplates();
    return;
  }

  if (args[0] === '--interactive' || args[0] === '-i') {
    interactive();
    return;
  }

  // Command-line mode
  const templateName = args[0];
  const params = {};
  let outputFile = null;

  for (let i = 1; i < args.length; i += 2) {
    const key = args[i].replace(/^--/, '');
    const value = args[i + 1];
    
    if (key === 'output') {
      outputFile = value;
    } else {
      params[key] = value;
    }
  }

  try {
    generator.generate(templateName, params, outputFile);
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = BadUSBGenerator;
